import { useCallback, useEffect, useState } from 'react';
import { ReactFlow, Background, MiniMap, Controls, addEdge, applyEdgeChanges, applyNodeChanges, BackgroundVariant, ReactFlowProvider, useReactFlow, type Connection, type EdgeChange, type NodeChange, type OnConnectEnd } from '@xyflow/react';
import { ActionIcon, AppShell, Badge, Button, Divider, Group, Menu, Modal, PasswordInput, Select, SimpleGrid, Stack, Tabs, Text, TextInput, Tooltip } from '@mantine/core';
import { Plus, Search, FolderOpen, History, Settings, Save, ChevronRight, FileText, Image, Video, Volume2, Upload, Command, Workflow, Users, Keyboard, CircleHelp, LayoutGrid, CheckSquare2, Trash2 } from 'lucide-react';
import { CreativeNode } from './CreativeNode';
import { useCanvasStore } from './store';
import { readProviderSettings, writeProviderSettings, type ProviderSetting } from './providerSettings';
import type { NodeKind } from './types';
import { listAssets, listGenerationJobs } from './api';

type Panel = 'assets' | 'characters' | 'history' | 'search' | 'shortcuts' | 'help' | 'settings';
const nodeTypes = { creative: CreativeNode };
const copy = { workspace: '\u672a\u547d\u540d\u5de5\u4f5c\u533a', saved: '\u5df2\u4fdd\u5b58', services: '4 \u4e2a\u6a21\u578b\u670d\u52a1', local: '\u672c\u5730\u5de5\u4f5c\u533a', settings: '\u8bbe\u7f6e', add: '\u6dfb\u52a0\u8282\u70b9', search: '\u8282\u70b9\u641c\u7d22', assets: '\u8d44\u4ea7\u5e93', characters: '\u89d2\u8272\u5e93', history: '\u5386\u53f2\u8d44\u4ea7', upload: '\u4e0a\u4f20\u672c\u5730\u7d20\u6750' };
const characterImages = ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=420&q=80','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=420&q=80','https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=420&q=80','https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=420&q=80','https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=420&q=80'];

function Workspace() {
  const { nodes, edges, setNodes, setEdges, select, addNode, hydrate, persist } = useCanvasStore();
  const [panel, setPanel] = useState<Panel | null>(null);
  const [serverAssets, setServerAssets] = useState<any[]>([]);
  const [jobs, setJobs] = useState<any[]>([]);
  const [connectionPicker, setConnectionPicker] = useState<{ x: number; y: number; startX: number; startY: number; position: { x: number; y: number }; sourceId: string; sourceKind: NodeKind } | null>(null);
  const { fitView, screenToFlowPosition, flowToScreenPosition, getNode } = useReactFlow();
  const onNodesChange = useCallback((changes: NodeChange[]) => setNodes(applyNodeChanges(changes, nodes) as typeof nodes), [nodes, setNodes]);
  const onEdgesChange = useCallback((changes: EdgeChange[]) => setEdges(applyEdgeChanges(changes, edges)), [edges, setEdges]);
  const onConnect = useCallback((connection: Connection) => setEdges(addEdge({ ...connection, animated: true }, edges)), [edges, setEdges]);
  const createAtCenter = useCallback((kind: NodeKind) => addNode(kind, screenToFlowPosition({ x: window.innerWidth / 2 - 250, y: window.innerHeight / 2 - 150 })), [addNode, screenToFlowPosition]);
  const onConnectEnd: OnConnectEnd = useCallback((event, state) => {
    if (state.isValid || !state.fromNode) return;
    const point = 'changedTouches' in event ? event.changedTouches[0] : event;
    const sourceKind = (state.fromNode.data as { kind?: NodeKind }).kind || 'text';
    const sourceNode = getNode(state.fromNode.id);
    const sourcePoint = flowToScreenPosition({ x: (sourceNode?.position.x || 0) + (sourceNode?.measured?.width || 500), y: (sourceNode?.position.y || 0) + 170 });
    setConnectionPicker({ x: point.clientX, y: point.clientY - 52, startX: sourcePoint.x, startY: sourcePoint.y, position: screenToFlowPosition({ x: point.clientX - 250, y: point.clientY - 150 }), sourceId: state.fromNode.id, sourceKind });
  }, [flowToScreenPosition, getNode, screenToFlowPosition]);
  useEffect(() => { void hydrate(); }, [hydrate]);
  useEffect(() => { const timer = window.setTimeout(() => { void persist(); }, 900); return () => window.clearTimeout(timer); }, [nodes, edges, persist]);
  useEffect(() => { if (panel === 'assets') void listAssets().then(setServerAssets).catch(() => undefined); if (panel === 'history') void listGenerationJobs().then(setJobs).catch(() => undefined); }, [panel]);
  return <AppShell header={{ height: 52 }} padding={0}>
    <AppShell.Header className="topbar"><Group justify="space-between" h="100%" px={14}><Group gap={10}><div className="brand">F</div><TextInput className="project-name" variant="unstyled" defaultValue={copy.workspace}/><Badge variant="light" color="teal" leftSection={<Save size={12}/>}>{copy.saved}</Badge></Group><Group gap={6}><Badge variant="default">{copy.services}</Badge><Tooltip label={copy.settings}><ActionIcon variant="subtle" color="gray" onClick={() => setPanel('settings')}><Settings size={17}/></ActionIcon></Tooltip><Button size="xs" variant="default">{copy.local}</Button></Group></Group></AppShell.Header>
    <AppShell.Main className="canvas-shell"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onConnectEnd={onConnectEnd} onNodeClick={(_, node) => select(node.id)} onPaneClick={() => { select(undefined); setConnectionPicker(null); }} fitView minZoom={0.15} maxZoom={2} colorMode="dark"><Background variant={BackgroundVariant.Dots} gap={22} size={1} color="#34373b"/><MiniMap position="bottom-right" pannable zoomable nodeColor="#464b51" maskColor="rgba(10,11,12,.72)"/><Controls position="bottom-left" showInteractive={false}/></ReactFlow>
      {connectionPicker && <ConnectionPicker
        sourceKind={connectionPicker.sourceKind}
        x={connectionPicker.x}
        y={connectionPicker.y}
        close={() => setConnectionPicker(null)}
        choose={(kind) => { const targetId = addNode(kind, connectionPicker.position); setEdges([...useCanvasStore.getState().edges, { id: `e-${connectionPicker.sourceId}-${targetId}`, source: connectionPicker.sourceId, target: targetId, animated: true }]); setConnectionPicker(null); }}
      />}
      {connectionPicker && <svg className="pending-connection" aria-hidden="true"><path d={`M ${connectionPicker.startX} ${connectionPicker.startY} C ${connectionPicker.startX + 90} ${connectionPicker.startY}, ${connectionPicker.x - 90} ${connectionPicker.y}, ${connectionPicker.x} ${connectionPicker.y}`}/></svg>}
      <nav className="floating-dock" aria-label="画布工具"><Menu position="top" width={180} shadow="xl"><Menu.Target><Tooltip label={copy.add}><ActionIcon size={42} radius="md" color="gray" variant="filled"><Plus size={23}/></ActionIcon></Tooltip></Menu.Target><Menu.Dropdown><Menu.Item leftSection={<FileText size={15}/>} onClick={() => createAtCenter('text')}>文本节点</Menu.Item><Menu.Item leftSection={<Image size={15}/>} onClick={() => createAtCenter('image')}>图像节点</Menu.Item><Menu.Item leftSection={<Video size={15}/>} onClick={() => createAtCenter('video')}>视频节点</Menu.Item><Menu.Item leftSection={<Volume2 size={15}/>} onClick={() => createAtCenter('audio')}>音频节点</Menu.Item></Menu.Dropdown></Menu><DockButton icon={Workflow} label="整理画布" onClick={() => fitView({ duration: 450, padding: 0.15 })}/><DockButton icon={LayoutGrid} label={copy.assets} onClick={() => setPanel('assets')}/><DockButton icon={Users} label={copy.characters} onClick={() => setPanel('characters')}/><DockButton icon={History} label={copy.history} onClick={() => setPanel('history')}/><Divider orientation="vertical"/><DockButton icon={Search} label={copy.search} onClick={() => setPanel('search')}/><DockButton icon={Keyboard} label="快捷键" onClick={() => setPanel('shortcuts')}/><DockButton icon={CircleHelp} label="帮助" onClick={() => setPanel('help')}/></nav>
      <WorkspaceModal panel={panel} close={() => setPanel(null)} nodes={nodes} serverAssets={serverAssets} jobs={jobs} selectNode={(id) => { select(id); setPanel(null); fitView({ nodes: [{ id }], duration: 450, maxZoom: 1 }); }}/>
    </AppShell.Main>
  </AppShell>;
}

function DockButton({ icon: Icon, label, onClick }: { icon: typeof Plus; label: string; onClick: () => void }) { return <Tooltip label={label} position="top"><ActionIcon size={34} variant="subtle" color="gray" onClick={onClick}><Icon size={18}/></ActionIcon></Tooltip>; }
const successors: Record<NodeKind, NodeKind[]> = { text: ['text','image','video'], image: ['image','video'], video: ['image','video'], audio: ['audio','video'], file: ['text','image','video'] };
const nodeChoices: Record<NodeKind, { label: string; icon: typeof FileText }> = { text: { label: '文本节点', icon: FileText }, image: { label: '图像节点', icon: Image }, video: { label: '视频节点', icon: Video }, audio: { label: '音频节点', icon: Volume2 }, file: { label: '文件节点', icon: FolderOpen } };
function ConnectionPicker({ sourceKind, x, y, choose, close }: { sourceKind: NodeKind; x: number; y: number; choose: (kind: NodeKind) => void; close: () => void }) { return <div className="connection-picker" style={{ left: x, top: y }}><Group justify="space-between" mb={7}><Text size="xs" c="dimmed">创建后继节点</Text><ActionIcon size="xs" variant="subtle" onClick={close}>×</ActionIcon></Group>{successors[sourceKind].map((kind) => { const ChoiceIcon = nodeChoices[kind].icon; return <Button key={kind} fullWidth variant="subtle" color="gray" justify="flex-start" leftSection={<ChoiceIcon size={15}/>} onClick={() => choose(kind)}>{nodeChoices[kind].label}</Button>; })}</div>; }
type CanvasNodes = ReturnType<typeof useCanvasStore.getState>['nodes'];
function WorkspaceModal({ panel, close, nodes, serverAssets, jobs, selectNode }: { panel: Panel | null; close: () => void; nodes: CanvasNodes; serverAssets: any[]; jobs: any[]; selectNode: (id: string) => void }) {
  const title = panel === 'assets' ? copy.assets : panel === 'characters' ? copy.characters : panel === 'history' ? copy.history : panel === 'search' ? copy.search : panel === 'shortcuts' ? '快捷键' : panel === 'settings' ? '模型服务' : '帮助';
  return <Modal opened={panel !== null} onClose={close} title={title} centered size="80vw" overlayProps={{ backgroundOpacity: 0.72, blur: 3 }} classNames={{ content: 'workspace-modal', body: 'workspace-modal-body', header: 'workspace-modal-header' }}>
    {panel === 'assets' && <Tabs defaultValue="image"><Group justify="space-between" mb="sm"><Tabs.List><Tabs.Tab value="image">图像 ({serverAssets.filter((a) => a.kind === 'image').length})</Tabs.Tab><Tabs.Tab value="video">视频 ({serverAssets.filter((a) => a.kind === 'video').length})</Tabs.Tab><Tabs.Tab value="audio">音频 (0)</Tabs.Tab></Tabs.List><Group><Button variant="default" leftSection={<CheckSquare2 size={15}/>}>批量操作</Button><Button leftSection={<Upload size={15}/>}>{copy.upload}</Button></Group></Group><Tabs.Panel value="image"><ServerAssetGrid assets={serverAssets.filter((a) => a.kind === 'image')}/></Tabs.Panel><Tabs.Panel value="video"><ServerAssetGrid assets={serverAssets.filter((a) => a.kind === 'video')}/></Tabs.Panel><Tabs.Panel value="audio"><EmptyState text="暂无音频素材"/></Tabs.Panel></Tabs>}
    {panel === 'characters' && <Stack><Group justify="space-between"><TextInput leftSection={<Search size={15}/>} placeholder="搜索角色" w={320}/><Button leftSection={<Plus size={15}/>}>创建角色</Button></Group><div className="featured-character"><div><Text fw={700} size="lg">角色参考集</Text><Text size="sm" c="dimmed">肖像、表情和三视图可持续关联到生成节点。</Text></div><Button variant="white" leftSection={<Plus size={15}/>}>应用到画布</Button></div><SimpleGrid cols={5} spacing="sm">{characterImages.map((src, index) => <div className="character-card" key={src}><img src={src}/><Text size="sm" fw={600}>角色 {index + 1}</Text><Text size="xs" c="dimmed">肖像参考</Text></div>)}</SimpleGrid></Stack>}
    {panel === 'history' && <Stack><Group justify="space-between"><Text fw={650}>生成任务</Text><TextInput leftSection={<Search size={15}/>} placeholder="搜索历史"/></Group><JobHistory jobs={jobs}/></Stack>}
    {panel === 'search' && <Stack><TextInput leftSection={<Search size={17}/>} placeholder="搜索标题、提示词或内容" size="md" autoFocus/>{nodes.map((node) => <Button key={node.id} variant="subtle" color="gray" justify="space-between" rightSection={<ChevronRight size={14}/>} onClick={() => selectNode(node.id)}><span>{node.data.title}</span><Text span size="xs" c="dimmed">{node.data.kind} / {node.data.model}</Text></Button>)}</Stack>}
    {panel === 'shortcuts' && <SimpleGrid cols={2}>{[['平移画布','空格 + 拖动'],['多选节点','Shift + 点击'],['删除节点','Backspace'],['适应画布','F'],['撤销','Ctrl + Z'],['重做','Ctrl + Shift + Z']].map(([name, key]) => <Group className="shortcut-row" justify="space-between" key={name}><Text size="sm">{name}</Text><Badge variant="default">{key}</Badge></Group>)}</SimpleGrid>}
    {panel === 'help' && <EmptyState text="使用顶部设置配置模型服务；从节点输出端口拖到空白处可创建下一节点。"/>}
    {panel === 'settings' && <ProviderSettingsPanel/>}
  </Modal>;
}

const emptySetting = (): ProviderSetting => ({ id: crypto.randomUUID(), kind: 'image', provider: '', displayName: '', modelId: '', baseUrl: '', apiKey: '' });
function ProviderSettingsPanel() {
  const [items, setItems] = useState<ProviderSetting[]>(readProviderSettings);
  const update = (id: string, patch: Partial<ProviderSetting>) => setItems((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item));
  const save = () => writeProviderSettings(items.filter((item) => item.displayName && item.modelId && item.baseUrl));
  return <Stack gap="md"><Group justify="space-between"><div><Text fw={650}>自定义模型服务</Text><Text size="xs" c="dimmed">显示名称与上游真实模型 ID 分开保存，避免名称冲突。</Text></div><Button leftSection={<Plus size={15}/>} variant="default" onClick={() => setItems((current) => [...current, emptySetting()])}>添加模型</Button></Group>
    {items.length === 0 && <EmptyState text="尚未配置自定义模型服务"/>}
    {items.map((item) => <div className="provider-setting" key={item.id}><SimpleGrid cols={3} spacing="sm"><Select label="节点类型" value={item.kind} allowDeselect={false} data={[{value:'text',label:'文本'},{value:'image',label:'图像'},{value:'video',label:'视频'}]} onChange={(value) => update(item.id, { kind: (value || 'image') as NodeKind })}/><TextInput label="供应商" value={item.provider} placeholder="火山方舟" onChange={(event) => update(item.id, { provider: event.currentTarget.value })}/><TextInput label="显示名称" value={item.displayName} placeholder="Seedream 4.5" onChange={(event) => update(item.id, { displayName: event.currentTarget.value })}/><TextInput label="真实模型 ID" value={item.modelId} placeholder="doubao-seedream-4-5-251128" onChange={(event) => update(item.id, { modelId: event.currentTarget.value })}/><TextInput label="Base URL" value={item.baseUrl} placeholder="https://api.example.com" onChange={(event) => update(item.id, { baseUrl: event.currentTarget.value })}/><PasswordInput label="API Key" value={item.apiKey} placeholder="sk-..." onChange={(event) => update(item.id, { apiKey: event.currentTarget.value })}/></SimpleGrid><Group justify="flex-end" mt="sm"><Button color="red" variant="subtle" leftSection={<Trash2 size={14}/>} onClick={() => setItems((current) => current.filter((entry) => entry.id !== item.id))}>移除</Button></Group></div>)}
    <Group justify="flex-end"><Button onClick={save}>保存模型服务</Button></Group>
  </Stack>;
}
function AssetGrid({ nodes }: { nodes: CanvasNodes }) { if (!nodes.length) return <EmptyState text="此分类暂无素材"/>; return <SimpleGrid cols={4} spacing="sm">{nodes.map((node) => <div className="asset-card" key={node.id}>{node.data.preview ? <img src={node.data.preview}/> : <div className="asset-placeholder"><Image size={34}/></div>}<Group justify="space-between" p="sm"><div><Text size="sm" fw={600}>{node.data.title}</Text><Text size="xs" c="dimmed">{node.data.provider || '本地'} / {node.data.model || '草稿'}</Text></div><Badge color={node.data.state === 'stale' ? 'orange' : 'teal'} variant="dot">{node.data.state}</Badge></Group></div>)}</SimpleGrid>; }
function HistoryList({ nodes }: { nodes: CanvasNodes }) { const items = nodes.filter((node) => node.data.state === 'succeeded' || node.data.state === 'stale'); if (!items.length) return <EmptyState text="暂无生成历史"/>; return <Stack gap={7}>{items.map((node) => <Group className="history-item" key={node.id} justify="space-between"><Group>{node.data.preview ? <img src={node.data.preview}/> : <div className="history-icon"><Command size={18}/></div>}<div><Text size="sm" fw={600}>{node.data.title}</Text><Text size="xs" c="dimmed">{node.data.provider} / {node.data.model}</Text></div></Group><Badge color={node.data.state === 'stale' ? 'orange' : 'teal'} variant="dot">{node.data.state}</Badge></Group>)}</Stack>; }
function ServerAssetGrid({ assets }: { assets: any[] }) { if (!assets.length) return <EmptyState text="此分类暂无素材"/>; return <SimpleGrid cols={4} spacing="sm">{assets.map((asset) => <div className="asset-card" key={asset.id}>{asset.objectKey ? <img src={asset.objectKey}/> : <div className="asset-placeholder"><Image size={34}/></div>}<Group justify="space-between" p="sm"><div><Text size="sm" fw={600}>{asset.name || '未命名素材'}</Text><Text size="xs" c="dimmed">{asset.source || '本地'}</Text></div><Badge variant="dot" color="teal">可用</Badge></Group></div>)}</SimpleGrid>; }
function JobHistory({ jobs }: { jobs: any[] }) { if (!jobs.length) return <EmptyState text="暂无生成任务"/>; const labels: Record<string,string> = { running:'生成中',succeeded:'已完成',failed:'失败',cancelled:'已取消',queued:'排队中',awaiting_confirmation:'等待确认' }; return <Stack gap={7}>{[...jobs].reverse().map((job) => <Group className="history-item" key={job.id} justify="space-between"><Group><div className="history-icon"><Command size={18}/></div><div><Text size="sm" fw={600}>{job.provider || '模型任务'} / {job.model || '未指定模型'}</Text><Text size="xs" c="dimmed">{new Date(job.createdAt).toLocaleString('zh-CN')}</Text></div></Group><Badge color={job.state === 'failed' ? 'red' : job.state === 'succeeded' ? 'teal' : 'blue'} variant="dot">{labels[job.state] || job.state}</Badge></Group>)}</Stack>; }
function EmptyState({ text }: { text: string }) { return <div className="modal-empty"><FolderOpen size={36}/><Text c="dimmed" size="sm">{text}</Text></div>; }
export function App() { return <ReactFlowProvider><Workspace/></ReactFlowProvider>; }
